apply plugin: 'com.android.application'

android {
    namespace 'com.xlythe.watchface.screenshots.provider'
    compileSdk 36

    defaultConfig {
        applicationId 'com.xlythe.watchface.screenshots.provider'
        minSdk 33
        targetSdk 36
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.wear.watchface:watchface-complications-data-source:1.2.1'
}
